use sha2::{Sha256, Digest};

pub fn generate_block_id(document_id: &str, sequence_index: usize, raw_text_content: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(document_id.as_bytes());
    hasher.update(sequence_index.to_string().as_bytes());
    hasher.update(raw_text_content.as_bytes());
    
    let result = hasher.finalize();
    format!("blk_{:x}", result)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_block_id_divergence() {
        // Known inputs and expected output to test against TS divergence
        let doc_id = "doc_12345";
        let seq_idx = 1;
        let content = "Chapter 1";
        
        let hash = generate_block_id(doc_id, seq_idx, content);
        // We will assert the expected hash generated by sha256("doc_123451Chapter 1")
        // "doc_123451Chapter 1" -> sha256 -> 195ab081eb5c17d383b16d1f04af5ce3e167f9ed30caec4f83ebc2efd0c75cc8
        assert_eq!(hash, "blk_195ab081eb5c17d383b16d1f04af5ce3e167f9ed30caec4f83ebc2efd0c75cc8");
    }
}
