// Mock expo-sqlite before importing schema so it doesn't crash on native imports
jest.mock('expo-sqlite', () => ({
  openDatabaseSync: jest.fn().mockReturnValue({
    execSync: jest.fn(),
  }),
}));

// Mock Node fs cleanly preserving actual fs methods for better-sqlite3
jest.mock('fs', () => {
  const actual = jest.requireActual('fs');
  return {
    ...actual,
    existsSync: jest.fn(),
    readFileSync: jest.fn(),
  };
});

import Database from 'better-sqlite3';
import { INITIALIZE_DATABASE_SCHEMA } from '../schema';
import { processDocumentJob } from '../worker';
import { ConnectorConfig } from '../../api/connector';
import { RustParserBridge } from '../../native/RustParserBridge';
import * as fs from 'fs';

describe('Multi-Format Ingestion Pipelines (EPUB, HTML, Markdown, PDF)', () => {
  let db: Database.Database;
  const corpId = 'corp-multi-123';
  const config: ConnectorConfig = {
    route: 'local',
  };

  beforeEach(() => {
    db = new Database(':memory:');
    db.exec(INITIALIZE_DATABASE_SCHEMA);

    // Seed collection metadata
    db.prepare("INSERT INTO corpora (id, name) VALUES (?, 'Test Collection');").run(corpId);
    jest.clearAllMocks();
  });

  afterEach(() => {
    db.close();
  });

  it('should ingest Markdown documents statically, parsing recursive heading hierarchies, styled blocks, list items, and highlights', async () => {
    const docId = 'doc-md-test';
    const filePath = 'sandbox/test.md';

    // Seed Markdown document metadata
    db.prepare(`
      INSERT INTO documents (id, corpus_id, title, source_type, sha256_hash, storage_path)
      VALUES (?, ?, 'Test MD', 'markdown', 'sha_md_123', ?);
    `).run(docId, corpId, filePath);

    const mockMdContent = `
# Chapter 1: Foundations
This is paragraph 1.
- First list item
- Second list item

## Section 1.1: Subtopic
Some subtopic block text containing <span class="highlight">crucial details</span> here.
> "A quotation to verify blockquote rendering"
    `;

    // Configure Node fs mocks
    (fs.existsSync as jest.Mock).mockReturnValue(true);
    (fs.readFileSync as jest.Mock).mockReturnValue(mockMdContent);

    const jobId = await processDocumentJob({
      db,
      documentId: docId,
      filePath,
      config,
    });

    expect(jobId).toBe(`job-${docId}`);

    // Verify sections (recursive headings)
    const sections = db.prepare('SELECT * FROM sections WHERE document_id = ? ORDER BY sort_order ASC;').all(docId) as any[];
    expect(sections.length).toBe(3); // Default Section, Chapter 1, Section 1.1
    expect(sections[0].title).toBe('Default Section');
    expect(sections[1].title).toBe('Chapter 1: Foundations');
    expect(sections[2].title).toBe('Section 1.1: Subtopic');
    expect(sections[2].parent_id).toBe(sections[1].id); // Recursive parent check!

    // Verify blocks
    const blocks = db.prepare('SELECT * FROM blocks WHERE document_id = ? ORDER BY sort_order ASC;').all(docId) as any[];
    expect(blocks.length).toBe(7); // heading 1, p1, list1, list2, heading 2, p2, quote

    // Verify quote styles
    const quoteBlock = blocks.find(b => b.block_type === 'quote');
    expect(quoteBlock).toBeDefined();
    expect(quoteBlock.content).toContain('A quotation to verify blockquote rendering');

    // Verify autogenerated annotations/highlights extraction from blocks content
    const annotations = db.prepare('SELECT * FROM annotations WHERE document_id = ?;').all(docId) as any[];
    expect(annotations.length).toBe(1);
    expect(annotations[0].highlighted_text).toBe('crucial details');

    // Verify dense vector_cache BLOB insertions
    const vectorCache = db.prepare('SELECT * FROM vector_cache;').all() as any[];
    expect(vectorCache.length).toBe(7);
    expect(Buffer.isBuffer(vectorCache[0].vector)).toBe(true); // Must be stored as binary BLOB!
  });

  it('should ingest HTML documents, stripping script/head elements and standardizing content into structured tables and blocks', async () => {
    const docId = 'doc-html-test';
    const filePath = 'sandbox/test.html';

    db.prepare(`
      INSERT INTO documents (id, corpus_id, title, source_type, sha256_hash, storage_path)
      VALUES (?, ?, 'Test HTML', 'html', 'sha_html_123', ?);
    `).run(docId, corpId, filePath);

    const mockHtmlContent = `
<!DOCTYPE html>
<html>
  <head>
    <title>Ignored Title</title>
    <script>console.log("dangerous script to strip");</script>
  </head>
  <body>
    <h1>Chapter 2: HTML structures</h1>
    <p>This is a paragraph under h1.</p>
    <table>
      <tr><td>Cell 1</td><td>Cell 2</td></tr>
    </table>
    <blockquote>HTML blockquote text</blockquote>
  </body>
</html>
    `;

    (fs.existsSync as jest.Mock).mockReturnValue(true);
    (fs.readFileSync as jest.Mock).mockReturnValue(mockHtmlContent);

    await processDocumentJob({
      db,
      documentId: docId,
      filePath,
      config,
    });

    // Verify sections and blocks
    const sections = db.prepare('SELECT * FROM sections WHERE document_id = ?;').all(docId) as any[];
    expect(sections.length).toBe(2); // Default and Chapter 2

    const blocks = db.prepare('SELECT * FROM blocks WHERE document_id = ?;').all(docId) as any[];
    expect(blocks.length).toBe(4);

    const tableBlock = blocks.find(b => b.block_type === 'table');
    expect(tableBlock).toBeDefined();
    expect(tableBlock.content).toContain('"type":"table"');

    // Verify FTS5 synchronization through database triggers
    const ftsResult = db.prepare("SELECT * FROM blocks_fts WHERE content MATCH 'structures';").all() as any[];
    expect(ftsResult.length).toBe(1);
  });

  it('should ingest EPUB documents, extracting spinal chapter sequences statically in one atomic transaction', async () => {
    const docId = 'doc-epub-test';
    const filePath = 'sandbox/test.epub';

    db.prepare(`
      INSERT INTO documents (id, corpus_id, title, source_type, sha256_hash, storage_path)
      VALUES (?, ?, 'Test EPUB', 'epub', 'sha_epub_123', ?);
    `).run(docId, corpId, filePath);

    await processDocumentJob({
      db,
      documentId: docId,
      filePath,
      config,
    });

    const sections = db.prepare('SELECT * FROM sections WHERE document_id = ? ORDER BY sort_order ASC;').all(docId) as any[];
    expect(sections.length).toBe(3); // 3 chapters (Introduction, Chapter 1, Chapter 2)

    const blocks = db.prepare('SELECT * FROM blocks WHERE document_id = ?;').all(docId) as any[];
    expect(blocks.length).toBe(6); // 3 headings + 3 paragraphs
  });

  it('should maintain perfect backwards compatibility for PDF documents running the two-pass LLM pipeline with resumption job chunks', async () => {
    const docId = 'doc-pdf-compat';
    const filePath = 'sandbox/compat.pdf';

    db.prepare(`
      INSERT INTO documents (id, corpus_id, title, source_type, sha256_hash, storage_path)
      VALUES (?, ?, 'PDF Compatibility', 'pdf', 'sha_pdf_123', ?);
    `).run(docId, corpId, filePath);

    // Mock JSI PDF parsing FFI call returning a PageExtraction payload
    const spyParsePDF = jest.spyOn(RustParserBridge, 'parsePDFAsync');

    // Mock Pass 2 LLM inference chat completion
    const spyFetch = jest.spyOn(global, 'fetch');
    spyFetch.mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        choices: [
          {
            message: {
              content: JSON.stringify({
                blocks: [
                  {
                    block_type: 'heading',
                    html_content: '<h2>PDF Compatibility Chapter</h2>',
                    hyperlink_targets: [],
                    semantic_tags: ['pdf', 'compatibility'],
                  },
                ],
              }),
            },
          },
        ],
      }),
    } as any);

    await processDocumentJob({
      db,
      documentId: docId,
      filePath,
      config: {
        route: 'network',
        endpoint: 'http://localhost:1234', // OpenAI standard format endpoint (does not trigger Ollama parse logic)
      },
    });

    expect(spyParsePDF).toHaveBeenCalledWith(filePath);
    expect(spyFetch).toHaveBeenCalled();

    // Verify PDF outputs
    const sections = db.prepare('SELECT * FROM sections WHERE document_id = ?;').all(docId) as any[];
    expect(sections.length).toBe(2); // Default and heading

    const blocks = db.prepare('SELECT * FROM blocks WHERE document_id = ?;').all(docId) as any[];
    expect(blocks.length).toBe(1);
    expect(blocks[0].content).toContain('PDF Compatibility Chapter');
  });

  it('should automatically cascade delete all associated relational table records (sections, blocks, block_tags, annotations, vector_cache) when a document is deleted', async () => {
    const docId = 'doc-cascade-test';
    const filePath = 'sandbox/cascade.md';

    db.prepare(`
      INSERT INTO documents (id, corpus_id, title, source_type, sha256_hash, storage_path)
      VALUES (?, ?, 'Test Cascade', 'markdown', 'sha_cascade_123', ?);
    `).run(docId, corpId, filePath);

    (fs.existsSync as jest.Mock).mockReturnValue(true);
    (fs.readFileSync as jest.Mock).mockReturnValue('# Cascade Heading\nSome content text <span class="highlight">marked</span>.');

    await processDocumentJob({
      db,
      documentId: docId,
      filePath,
      config,
    });

    // Check that sections, blocks, annotations, and vector caches are populated
    expect((db.prepare('SELECT COUNT(*) as count FROM sections;').get() as any).count).toBeGreaterThan(0);
    expect((db.prepare('SELECT COUNT(*) as count FROM blocks;').get() as any).count).toBeGreaterThan(0);
    expect((db.prepare('SELECT COUNT(*) as count FROM vector_cache;').get() as any).count).toBeGreaterThan(0);
    expect((db.prepare('SELECT COUNT(*) as count FROM annotations;').get() as any).count).toBeGreaterThan(0);

    // Delete document (ON DELETE CASCADE should trigger)
    db.prepare('DELETE FROM documents WHERE id = ?;').run(docId);

    // Verify EVERYTHING is cascaded out completely
    expect((db.prepare('SELECT COUNT(*) as count FROM documents WHERE id = ?;').get(docId) as any).count).toBe(0);
    expect((db.prepare('SELECT COUNT(*) as count FROM sections;').get() as any).count).toBe(0);
    expect((db.prepare('SELECT COUNT(*) as count FROM blocks;').get() as any).count).toBe(0);
    expect((db.prepare('SELECT COUNT(*) as count FROM vector_cache;').get() as any).count).toBe(0);
    expect((db.prepare('SELECT COUNT(*) as count FROM annotations;').get() as any).count).toBe(0);
    expect((db.prepare('SELECT COUNT(*) as count FROM block_tags;').get() as any).count).toBe(0);
  });
});
