// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Annotation = { id: string, document_id: string, block_id: string | null, annotation_type: string, color_code: string, highlighted_text?: string, note_body?: string, anchor_metadata?: string, created_at?: string, updated_at?: string, };