// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Document = { id: string, title: string, sha256_hash: string, author?: string, source_type?: string, };