// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtractionChunk = { document_id: string, chunk_index: number, raw_text: string, };