// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractedImageMetadata } from "./ExtractedImageMetadata";
import type { LayoutHint } from "./LayoutHint";

export type PageExtraction = { document_id: string, page_number: number, overlap_context: string, raw_text: string, layout_hints: Array<LayoutHint>, extracted_images: Array<ExtractedImageMetadata>, };