// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ASTNode } from "./ASTNode";
import type { BlockType } from "./BlockType";

export type ExtractedBlock = { block_type: BlockType, content: ASTNode, hyperlink_targets: Array<string>, semantic_tags: Array<string>, };