// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentIndex } from "./DocumentIndex";

export type ExtractedMetadata = { "type": "index", "data": DocumentIndex } | { "type": "tags", "data": Array<string> } | { "type": "summary", "data": string };