// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtractedImageMetadata = { image_id: string, sha256_hash: string, bounding_box: [number, number, number, number], page_width: number, page_height: number, local_uri: string, };