// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ASTNode } from "./ASTNode";

export type ListItem = { children: Array<ASTNode>, };