// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractedBlock } from "./ExtractedBlock";

export type LLMStructuringOutput = { blocks: Array<ExtractedBlock>, };