// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StructuredSection = { id: string, parent_id: string | null, title: string, depth_level: number, sort_order: number, };